app/models.py
from app import db, login_manager
from flask_login import UserMixin
from datetime import datetime
from werkzeug.security import generate_password_hash





class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True )
    first_name = db.Column(db.String, nullable=False)
    last_name = db.Column(db.String, nullable=False)
    email = db.Column(db.String, nullable=False)
    password = db.Column(db.String)
    created_on = db.Column(db.DateTime, default= datetime.utcnow)
    post= db.relationship('Post',backref='author', lazy='dynamic')

    

    



    def hash_password(self, signup_password):
        return generate_password_hash(signup_password)   

    def from_dict(self, user_data):
        self.first_name = user_data['first_name']
        self.last_name = user_data['last_name']
        self.email = user_data['email']
        self.password = self.hash_password(user_data['password'])

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


    
class Post(db.Model):
    id=db.Column(db.Integer, primary_key=True)
    img_url=db.Column(db.String)
    title=db.Column(db.String)
    caption=db.Column(db.String)
    created_on=db.Column(db.DateTime, default=datetime.utcnow())
    user_id=db.Column(db.Integer, db.ForeignKey('user.id'))

    def from_dict(self, post_data):
        self.img_url= post_data['img_url']
        self.title=post_data['title']
        self.caption=post_data['caption']
        self.user_id=post_data['user_id']

app/blueprints/main/forms.py
# from flask_wtf import FlaskForm
# from wtforms import EmailField, PasswordField, SubmitField,StringField
# from wtforms.validators import DataRequired, EqualTo

app/forms.py
from flask_wtf import FlaskForm
from wtforms import EmailField, PasswordField, SubmitField,StringField
from wtforms.validators import DataRequired, EqualTo

class LoginForm(FlaskForm):
    email = EmailField('Email:',  validators=[DataRequired()])
    password = PasswordField('Password:', validators=[DataRequired()])
    submit = SubmitField('Login')

class PokeForm(FlaskForm):
    poke_request = StringField('Pokemon', validators=[DataRequired()])
    submit_1=SubmitField('I Choose you')

class Signup_form(FlaskForm):
    first_name = StringField('First Name:', validators=[DataRequired()])
    last_name = StringField('Last Name:', validators=[DataRequired()])
    email = EmailField('Email:', validators=[DataRequired()])
    password = PasswordField('Password:', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password:', validators=[DataRequired(), EqualTo('password')])
    submit_2= SubmitField('Sign Up')

app/__init__.py
from flask import Flask
from config import Config
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate






login_manager = LoginManager()
db = SQLAlchemy()



migrate = Migrate()

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    
    # registering packages
    login_manager.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)

    # login settings
    login_manager.login_view='auth.login'
    login_manager.login_message = 'You must be logged in to visit this page'
    login_manager.login_message_category= 'warning'
    

    # importing blueprints
    from app.blueprints.main import main
    from app.blueprints.auth import auth
    from app.blueprints.post import post

    # registering blueprints
    app.register_blueprint(main)
    app.register_blueprint(auth)
    app.register_blueprint(post)

    return app

# from app import models

app/blueprints/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__ )

from . import routes

app/blueprints/main/routes.py
from flask import request, render_template, flash,redirect,url_for
import requests
from . import main
from flask_login import login_required, current_user
from app.models import User






@main.route('/')
@main.route('/home')
def home():
    
    
    return render_template('home.html' )

@main.route('/user/<username>')
def username(username):
    return  f'Hello today {username}'

@main.route('/post/<int:post_id>')
def show_post(post_id):
    # show the post with the given id, the id is an integer
    return f'Post {post_id}'




@main.route('/products',  methods=['GET', 'POST'])
def product():
    
    return render_template('product.html')

app/blueprints/post/__init__.py
from flask import Blueprint

post= Blueprint('post', __name__, template_folder='post_templates', url_prefix='/post')

from . import routes

app/blueprints/post/routes.py
from . import post
from .form import PostForm
from flask import request, flash, redirect, url_for,render_template
from flask_login import current_user
from app.models import Post
from app import db

@post.route('/create_post', methods=['GET', 'POST'])
def create_post():
    form=PostForm()
    if request.method == 'POST' and form.validate_on_submit():
    #    this is coming from the post form
        post_data = {
                'img_url':form.img_url.data,
                'title':form.title.data,
                'caption':form.caption.data,
                'user_id': current_user.id

        }

        # Create a Post Instance
        new_post = Post()

        # Set post_data to our post attributes
        new_post.from_dict(post_data)

        db.session.add(new_post)
        db.commit()

        flash('Successfully created post', 'success')
        return redirect(url_for('main.home'))
    else:
        return render_template('create_post.html', form=form)

app/templates/Login.html
{% extends 'base.html' %}
{% block title %}

{% endblock %}
{% block content %}
    
   <h1 class="text-center">App Login Page</h1>     
   <div id= "form-container" >
        <div>
            <form action="" method="POST">
                    {{form.hidden_tag()}}
                <div>
                    <div class="form-group">
                        {{form.email.label}}
                        {{form.email(class= "form-control") }}
                        <small id="emailHelp" class="form-text ">We'll never share your email with anyone else.</small>
                    </div>
                    <div class="form-group">
                        {{form.password.label}}
                        {{form.password(class="form-control")}}
                    </div>
                    <div class="logbtn"> {{form.submit(class="btn")}}</div>
                </div>      
            </form>
               {% if error %} 
                    <p class="text-center text-danger">{{ error }}</p>  
                {% endif %}
            
            
        </div>
   </div>    
   
 
 
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <link rel=" stylesheet" href="{{url_for('static',filename='css/styles.css')}}">


  <link rel="apple-touch-icon" sizes="180x180" href="{{url_for('static', filename='images/apple-touch-icon.png')}}">
  <link rel="icon" type="image/png" sizes="32x32" href="{{url_for('static', filename='images/favicon-32x32.png')}}">
  <link rel="icon" type="image/png" sizes="16x16" href="{{url_for('static', filename='images/favicon-16x16.png')}}">
  <link rel="manifest" href="{{url_for('static', filename='images/site.webmanifest')}}">

  <title>{% block title%} {% endblock %}</title>




</head>

<body>
  <div>
    <nav id="connav" class="navbar navbar-expand-lg navbar-light ">
      <a class="navbar-brand" href="#">Contrast Beads</a>
      <button id="nav_btn" class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{{url_for('main.home')}}">Home <span
                class="sr-only">({{current_user.first_name}})</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('auth.signup')}}">SignUp</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{url_for('auth.logout')}}">Logout</a>
              <a class="dropdown-item" href="{{url_for('auth.login')}}">Login</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{{url_for('main.product')}}">Shop Here</a>
            </div>
          </li>

        </ul>

        <form class="my-2 my-lg-0">
          <div class="row">
            <div class="col-sm-8">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            </div>
            <div class="col-sm-4">
              <button id="nav_btn" class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </div>
          </div>
        </form>
      </div>

  </div>
  </nav>
  <!-- <nav class="navbar navbar-dark bg-dark ">
            <div class="container-fluid">
              <a class="navbar-brand" href="{{url_for('main.home')}}">Poke App 1.0 </a>              <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
                <div class="offcanvas-header">
                  <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">{{current_user.first_name}}</h5>
                  <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                  <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    {%if current_user.is_authenticated %}
                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{{url_for('main.home')}}">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Things to do
                      </a>
                      <ul class="dropdown-menu dropdown-menu-dark">Pokemon                         <li><a class="dropdown-item" href="{{url_for('main.home')}}">Search a </a></li>
                         <li><a class="dropdown-item" href="{{url_for('post.create_post')}}">Create a Post</a></li>
                        <li><a class="dropdown-item" href="{{url_for('auth.logout')}}">Logout</a></li>
                        <li>
                          <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                        {% else %}
                   
                    <li class="nav-item">
                      <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{{url_for('auth.signup')}}">Create Profile</a>
                    </li>
                    {%endif%}
                    
                      </ul>
                    </li>
                  </ul>
                  <form class="d-flex mt-3" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-success" type="submit">Search</button>
                  </form>
                </div>
              </div>
            </div>
          </nav>  -->
  {%with messages = get_flashed_messages(with_categories=true)%}
  {%if messages%}
  {%for category, message in messages%}
  <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
    <strong>{{message}}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">

    </button>
  </div>
  {%endfor%}

  {%endif%}
  {%endwith%}
  </div>
  {% block content %}

  {% endblock %}
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
</body>

</html>

app/templates/home.html
{% extends 'base.html' %}
{% block title %}

{% endblock %}
{% block content %}
<h1>This is the Home Page</h1>




{% endblock %}

app/templates/product.html
{% extends 'base.html' %}
{% block title %}
<h1>Product Page</h1>

{% endblock %}
{% block content %}



{% endblock %}   

app/templates/signup.html
{% extends 'base.html' %}
{% block title %}

{% endblock %}
{% block content %}
    
        
   <div id="form-container_1">
        <div>
            <form action="" method="POST">
                    {{form.hidden_tag()}}
                <div>
                    <div class="form-group" >
                        {{form.first_name.label}}
                        {{form.first_name(class="form-control")}}
                    </div>
                    <div class="form-group">
                        {{form.last_name.label}}
                        {{form.last_name(class="form-control")}}
                    </div>
                    <div class="form-group">
                        {{form.email.label}}
                        {{form.email(class="form-control") }}
                    </div>
                    <div class="form-group">
                        {{form.password.label}}
                        {{form.password(class="form-control") }}
                    </div>
                    <div>
                        {{form.confirm_password.label}}
                        {{form.confirm_password(class="form-control")}}
                    </div>
                    
                    <div class ="logbtn"> {{form.submit_2(class="btn btn-primary")}}</div>
                </div>      
            </form>
                
            
        </div>
   </div>    
   
 
 
{% endblock %}